Login backend
JuhoBjn/online-store pull request #24
Opened 2023-09-28 22:11 UTC by JuhoBjn

* Defined database tables for users and user roles
* Wrote unit tests for signup and login API endpoints
* Implemented MySQL connection pool
* Implemented signup API endpoint
* Implemented login API endpoint

Closes #20

2023-09-30 00:35 UTC, vaasuu requested changes
Works great, Good job! 
Please check the comments and suggested changes; at least the name splitting change DB migration is important to address.

2023-09-30 00:35 UTC, vaasuu commented on backend/models/users.js
> +    return rows;
In SQL, the `HAVING` clause is typically used with aggregate functions, whereas the `WHERE` clause is used to filter rows based on specific conditions. Since you are filtering rows based on the email value, using `WHERE` is more appropriate.

```suggestion
      LEFT JOIN roles ON users.role_id = roles.id
      WHERE email = ?;`;
    const [rows] = await promisePool.query(queryString, [email]);
    return rows;
```

2023-09-30 11:51 UTC, JuhoBjn commented on backend/db/migrations/20230926173433_add_role_to_user.sql
> +
I moved the name separation to the create_users_table migration and removed it from add_role_to_user.  Also fixed the `migrate:down` script. The syntax for dropping the foreign key `fk_users_roles_idx` was invalid and the `role_id` column was not being deleted.

2023-09-30 14:18 UTC, JuhoBjn commented on backend/models/users.js
> +   */
Fixed this in 1f1ff84953abb8dc32edf499077beddb33b0b242

2023-09-30 14:18 UTC, JuhoBjn commented on backend/models/users.js
> +   */
Fixed in 1f1ff84953abb8dc32edf499077beddb33b0b242

2023-09-30 14:20 UTC, JuhoBjn commented on backend/models/users.js
> +   */
Also I updated the `findByEmail` method to return only the user object or null since there will only every be one user for each email. 13d329571c97bcedd72234a0bb09a10cc493ef71

2023-09-30 14:24 UTC, JuhoBjn commented on backend/models/users.js
> +  }
Fixed this in 3aba92be011a8fb7d6a7a723ca2c773e719210a3. Tried this before without success, turns out I needed a second set of square brackets to make the destructuring work.

2023-09-30 14:26 UTC, JuhoBjn commented on backend/models/users.js
> +    return rows;
Fixed this in 0465471dfd288e78185c9defd3a20e8e73cab08e

2023-09-30 17:40 UTC, vaasuu approved these changes
Looks good to me

2023-10-01 09:13 UTC, Jypaa approved these changes

2023-10-01 16:22 UTC, merged