Jyri/profile
JuhoBjn/online-store pull request #42
Opened 2023-10-16 18:44 UTC by Jypaa

can edit profile informations

2023-10-17 15:05 UTC, JuhoBjn requested changes
Overall, a good start. I'd like to see some more tests for the endpoint to try all updating all the different parts of a user's profile with valid and invalid inputs. I left some suggestions as comments for you to check out.

2023-10-19 17:08 UTC, vaasuu requested changes
I also added some comments. Probably the main suggestion being getting userid from url instead of request body. 
Couple more tests to make sure everything is working (at least a good patch, bad patch & patch with multiple things at once) would also be really appreciated.
Also adding the endpoint to the RESTClient file would be good.

2023-10-23 12:42 UTC, Jypaa commented on backend/__tests__/user.test.js
> +  }, 1000000000);
:D it was for debugging and forgot to change back to five sec.

2023-10-23 12:44 UTC, Jypaa commented on backend/routes/users.js
> +router.patch("/updateuser", updateUser);
added "router.use(checktoken)" but is still commented off, because didn't had any rights after it was added. Changed api route.

2023-10-23 12:48 UTC, Jypaa commented on backend/__tests__/user.test.js
> +    country: "se",
it was because test are running simultaneously, so there  was some errors with similar details, so I made fast solutions for problem.

2023-11-07 09:44 UTC, vaasuu approved these changes
LGTMETIHRCI (Looks good to me even though I haven't really checked it)

2023-11-07 09:44 UTC, JuhoBjn approved these changes
lgtm

2023-11-07 09:45 UTC, merged