Get/delete endpoint
JuhoBjn/online-store pull request #63
Opened 2023-10-30 18:58 UTC by Jypaa

Added endpoint for get user by id, get all users and delete user by id.

2023-11-01 12:02 UTC, JuhoBjn requested changes
I left some comments for you to check out.

2023-11-01 13:04 UTC, Jypaa commented on backend/models/users.js
> +    await promisePool.query(deleteQuery, [id], (err) => {
If I take it off then it tries to run other tests while it is still deleting user.

2023-11-01 20:33 UTC, vaasuu requested changes
I left some comments

2023-11-01 20:33 UTC, vaasuu commented on backend/controllers/users.js
> +
Add check: User should only be able to delete their own account.
Currently anyone can delete someone else's account!

2023-11-01 20:33 UTC, vaasuu commented on backend/controllers/users.js
> +    res.status(200).json(response);
Do not return everything (including password hashes!), only some things like id, name, postcode, city ?

2023-11-01 20:33 UTC, vaasuu commented on backend/controllers/users.js
> +    id: Joi.string().required()
Id type should be uuid

2023-11-01 20:33 UTC, vaasuu commented on backend/controllers/users.js
> +    res.status(200).json(response);
Do not return everything (like password hash).

2023-11-01 23:26 UTC, Jypaa commented on backend/controllers/users.js
> +  }
I was thinking that if it gets response which it should not get, then throw error code, but maybe 404 is not right one.

2023-11-07 09:46 UTC, JuhoBjn approved these changes

2023-11-07 09:46 UTC, vaasuu approved these changes

2023-11-07 09:46 UTC, merged